title: Academic and Research
description: ğŸ‘‹ Hi, Iâ€™m Folagbade Abitogun
ğŸ‘€ Iâ€™m a writer. I write across different fields and industries. This repo is dedicated to my academic and research writing. Here, I will be uploading discussing some of my academic and research content, with the aim of carrying you along. with my writing process for each writing task I have from my clients.
ğŸŒ± Iâ€™m currently learning cybersecurity. Yes! This is one of the many fields I hope to start writing on very soon. So, I better continue learning, right? Also, Python got my attention and you can be sure I am going to pick it up.
ğŸ’ï¸ Iâ€™m looking to collaborate on writing gigs and cybersecurity career information and activities. If you havw writng tasks that are being outsourced, I will be more than interested to discuss it with you

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
